import { useState, useEffect } from 'react'
import Head from 'next/head'
import ProductDetail from './product-detail'
import { GetProductsContext } from '../context/ProductsContext'
import { getProductDetails } from '../services/wocommerce'
import PrimaryButton from '../components/buttons/PrimaryLinkButton'

export default function Home(props) {
  
  const { products, setProducts } = GetProductsContext()
  const [ loading, setLoading ] = useState(true)

  useEffect(() => {
    getProductDetails(setProducts, setLoading)
  }, [])

  console.log(products)

  return (
    <>
      <Head>
        <title>Rent Internet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        loading ?
        '...loading' :
        <PrimaryButton to='product-detail'>Rent</PrimaryButton>
      }
    </>
  )
}